### ISSUE TITLE
Redesigning conda-forge.org

### ISSUE THREAD

**Issue by jaimergp** [conda-forge/conda-forge.github.io#1971]
Hello conda-forge!

We now have a new website prototype available at https://cf-infra-docs.netlify.app/. This mostly showcases the work @asmitbm did during his GSoC internship last summer, but you can also see how some documentation would look like there, or the blog.

This prototype is based on the Docusaurus framework, which uses a React, Node and Markdown. 

In parallel, @afshin has been working on a new status page in [this PR](https://github.com/Quansight-Labs/cf-infra-docs/pull/12). [A preview is also available](https://deploy-preview-12--cf-infra-docs.netlify.app/status/).

I've also done some work studying potential migration strategies for our documentation. I don't want to lose the valuable git history by converting all the RST over to MD, so instead I suggest the following strategy:

1. Keep Sphinx around for now, but have it render to Markdown instead of HTML (via `sphinx-markdown-builder`).
2. Have Docusaurus take those Markdown documents and render the HTML with them.
3. Whenever needed, slowly migrate RST content to native MD in Docusaurus. This might never happen though, if we feel that Sphinx's linking abilities are too important. We can also end up in a hybrid situation, with some narrative documentation being rendered natively in Docusaurus, and some more reference-y docs done in Sphinx.

I have a demo of how this strategy works in https://github.com/Quansight-Labs/cf-infra-docs/pull/14. [Plus the corresponding preview](https://deploy-preview-14--cf-infra-docs.netlify.app/docs/).

---

### Migration steps

This is my proposed timeline:

- [x] 1. Implement Docusaurus in this repository, starting with the frontpage _only_. Ensure there are no broken links - https://github.com/conda-forge/conda-forge.github.io/pull/2050
- [x] 2. Migrate the blog ([the preview site already has it](https://cf-infra-docs.netlify.app/blog/)), while keeping git credits around.
- [x] 3. Migrate `feedstock-outputs`
  - [x] Frontend: https://github.com/conda-forge/conda-forge.github.io/pull/2064
  - [X] Backend should produce JSON: https://github.com/conda-forge/feedstock-outputs/pull/58
- [x] 4. Migrate the Sphinx documentation as discussed above.
  - [x] Migrate announcements to a new blog-like instance - https://github.com/conda-forge/conda-forge.github.io/pull/2057
  - [X] Migrate most of the Orga content to a new community docs-like instance: https://github.com/conda-forge/conda-forge.github.io/pull/2093
  - [x] Expose the rest of the documentation as is (in the future, we'll do more work to reorganise some bits). #2077 
- [x] 5. Migrate the status page:
  - [X] https://github.com/conda-forge/conda-forge.github.io/pull/2090
  - [x] https://github.com/conda-forge/status/pull/172
  - [x] Dark mode: https://github.com/conda-forge/conda-forge.github.io/pull/2090#issuecomment-1988228279 & https://github.com/conda-forge/conda-forge.github.io/pull/2090#issuecomment-1985493082
  - [x] UX in migration details: https://github.com/conda-forge/conda-forge.github.io/pull/2090#issuecomment-1979121823
- [x] 6. Add more visibility to the [Miniforge website](https://conda-forge.org/miniforge), possibly matching the new website style.
- [x] Other items:
  - [X] Search with Algolia #2077
  - [X] Statistics with Goatcounter #2077

Thoughts, @conda-forge/core?

**Comment by asmitbm** [comment]
Happy to get feedback from the community :D

**Comment by jaimergp** [comment]
This is a preview of you can see in the Figma file:

Some proposals for the main header in the frontpage:

![image](https://github.com/conda-forge/conda-forge.github.io/assets/2559438/fc1590fb-72cd-4381-8b15-db43ac9078a0)

Some proposals for the "conda-forge by the numbers" section:

![image](https://github.com/conda-forge/conda-forge.github.io/assets/2559438/06f7c22f-f223-4e65-9bff-a1e45a6d4416)


Contributing:

![image](https://github.com/conda-forge/conda-forge.github.io/assets/2559438/49f17fc6-453a-49c3-9023-30a12d3b06cd)

![image](https://github.com/conda-forge/conda-forge.github.io/assets/2559438/0b16a3cd-d4ae-4f34-887e-3a29473f61fa)


The color palette:

![image](https://github.com/conda-forge/conda-forge.github.io/assets/2559438/3d5c718b-90a2-4290-bd4f-bf27ae0ffdc4)

**Comment by jakirkham** [comment]
Thanks Jaime! 🙏

What level of feedback are you looking for at this stage?

**Comment by jakirkham** [comment]
Sorry let me clarify.

Is this meant as a high-level rough sketch of what you would like to do? If so, then comments would be about colors, layout, etc

Or is this meant to go as-is? If so, comments would focus on missing links, typos, etc.

Does that make more sense? Which of those are you going for? Or something else entirely?

**Comment by jaimergp** [comment]
Ah ok, thanks for clarifying.

The design is mostly settled now. We didn't get feedback back then (see hidden comments) so we had to assume folks were ok with our choices. We might fine tune some elements (i.e. the different states of the links), though, so if you have feedback in that direction, of course it's welcome. The currently proposed frontpage follows the conda-forge.org frontpage almost 1:1 in content, although it has been redesigned.

That said, I'd like to focus on the transition to a new framework now without losing information in the way (no broken links, all functionality in place, etc). Once we are using the new framework we can easily submit PRs to adjust things.

Let me know if you need more details, happy to provide them. It looks like we could start with a PR for point (1), right?

**Comment by beckermr** [comment]
The colors are not to my liking. Can we work on them?

**Comment by beckermr** [comment]
I think we chatted about the colors a few weeks ago?

**Comment by beckermr** [comment]
suggestions from @wolfv on colors

 - https://coolors.co/edf0da-f0dfad-8f2d56-ff6542-218380
 - https://coolors.co/1be7ff-6eeb83-e4ff1a-ff6542-e8aa14

**Comment by jaimergp** [comment]
Hello @conda-forge/core, @isabela-pf has shared three palettes I'm presenting below. Still preliminary and might need a few touches here and there, but these are ready for comments.

In Isabela's words:

> I tried to keep to warmer colors to continue the "forge" feeling while avoiding conda green or the red, orange, and yellows that tend to give contrast issues. The blues have a little more hot-flame yellow in them, and the magenta is a little more ember-like.

See them in action:

* [Teal live preview](https://deploy-preview-16--cf-infra-docs.netlify.app/) (https://github.com/Quansight-Labs/cf-infra-docs/pull/16)
* [Cyan live preview](https://deploy-preview-17--cf-infra-docs.netlify.app/) (https://github.com/Quansight-Labs/cf-infra-docs/pull/17)
* [Magenta live preview](https://deploy-preview-18--cf-infra-docs.netlify.app/) (https://github.com/Quansight-Labs/cf-infra-docs/pull/18)

Try the dark/light theme switcher in the top bar to try both modes! 
<img width="300" alt="image" src="https://github.com/conda-forge/conda-forge.github.io/assets/2559438/29471d7b-b3d6-4006-a94d-7d235e69f468">


If you ask me for my preferences, I really like the magenta, then cyan, and finally teal, but I would be happy with all of them. Please let us know if you have a preference!

**Comment by hmaarrfk** [comment]
All 3 are beautiful in my mind ;)

**Comment by h-vetinari** [comment]
I agree that they all look great! Personally, I think the magenta one is the most aggressive, contrast-wise, so my order of preference is:
1. teal
2. cyan
3. magenta

**Comment by jaimergp** [comment]
Cool! Yes, that matches what I'm seeing in an informal survey in the Quansight Slack:

* Teal: 11
* Cyan: 5
* Magenta: 4

**Comment by jakirkham** [comment]
Would be ok with Teal or Cyan. Magenta is too close to the red we wanted to move away from. Also is there an optical illusion at play or does Cyan have a gradient across it?

<hr>

For completeness, am writing down notes from the previous core meeting when we reviewed the new webpage together:

* Side bar menu - This is nice! Could it also float? So following the user down the page as they scroll.
* Links - 1st or 2nd layer in docs seem to have broken links (based on a handful I tried). Might be worth running linkcheck or similar to just validate all links are working.
* Status page
  * Current progress bars show done and everything else
    * This loses some gradation that the current progress bars have (done, in-pr, awaiting-pr, not-solvable, awaiting-parents, bot-error)
    * Ideally would keep at least (done, in-pr, everything else)
    * Maybe in-pr could be gray (instead of black or white) or something to call out it is in-between done and awaiting
  * Anchors appear to be missing. In the current status page one can anchor to [the Arch migration]( https://conda-forge.org/status/#aarch64andppc64leaddition ), [Long-term migrations]( https://conda-forge.org/status/#big_migrations ), or some [specific migration]( https://conda-forge.org/status/#libeantic2 ). This appears to not be available in the current status page. It would be nice to include anchors so we can point people to more specific migrations or other details.

**Comment by jaimergp** [comment]
> Also is there an optical illusion at play or does Cyan have a gradient across it?

All of them have a gradient in the frontpage :D 

> For completeness, am writing down notes from the previous core meeting when we reviewed the new webpage together

Noted!

**Comment by jaimergp** [comment]
I've merged the teal theme with some adjustments. I'll create issues for the pending tasks.

> Side bar menu - This is nice! Could it also float? So following the user down the page as they scroll.

I think it does already. It's more noticeable in long docu pages, [like this one](https://cf-infra-docs.netlify.app/docs/fundamentals/life-cycle/). In short pages where the footer is already showing up, then it resumes the scrolling.

**Comment by jaimergp** [comment]
New homepage is live!

**Comment by jaimergp** [comment]
[`feedstock-outputs`](https://conda-forge.org/feedstock-outputs/) has lost its theming 😬 Still works, but it has reverted to factory bootstrap and the top bar is now partially hidden by the header. I can work on a new iteration that matches the new homepage, or simply change the link to https://conda-metadata-app.streamlit.app/. Thoughts?

**Comment by beckermr** [comment]
I think all we need to do is to move the CSS or w/e to the right path?

**Comment by beckermr** [comment]
paths are in this file: https://github.com/conda-forge/feedstock-outputs/blob/gh-pages/index.html

We can change them there too.

**Comment by asmitbm** [comment]
I can help design that page? My idea earlier was to design a card with name and its version as seen on conda metadata site. Thoughts?

**Comment by beckermr** [comment]
Sure! The search integration was done by hand so we'd need to ensure that translates.

**Comment by asmitbm** [comment]
> Sure! The search integration was done by hand so we'd need to ensure that translates.

Cool, I’ll first post figma designs here for feedback and reviews. Then work on implementing it.

**Comment by beckermr** [comment]
This commit should fix things for now: https://github.com/conda-forge/conda-forge.github.io/commit/7d632fd510c4dff83540964cf28d4e123f8aa5c1

**Comment by jaimergp** [comment]
Thanks for the quick fix @beckermr! I didn't realize it was _that_ simple 😂 

When I was thinking of redesigning that page, I had these ideas in mind:

* Change `conda-forge/feedstock-outputs` to generate a JSON map instead of the rendered version of the HTML. This can be a bit fat, but the HTML alone is already 8.7MB 🤷 
* Add a JSX page in the Docusaurus website that knows how to fetch that JSON (similar to what the by-the-numbers components are doing in the frontpage) and display it with a search component (not sure how to do this right now, maybe there's something React-y we can use?).

WDYT? cc @asmitbm

**Comment by asmitbm** [comment]
> Thanks for the quick fix @beckermr! I didn't realize it was _that_ simple 😂
> 
> When I was thinking of redesigning that page, I had these ideas in mind:
> 
> * Change `conda-forge/feedstock-outputs` to generate a JSON map instead of the rendered version of the HTML. This can be a bit fat, but the HTML alone is already 8.7MB 🤷
> * Add a JSX page in the Docusaurus website that knows how to fetch that JSON (similar to what the by-the-numbers components are doing in the frontpage) and display it with a search component (not sure how to do this right now, maybe there's something React-y we can use?).
> 
> WDYT? cc @asmitbm

This idea seems cool and easier to integrate with Docusaurus. If there's any way we can get a JSON output, I can implement the new page. 

This [file](https://github.com/conda-forge/conda-forge.github.io/blob/81e361bd2763aa72eabf0a2fdb2e7f52f4660341/sphinx/feedstock_outputs.html.tmpl#L111) is already using templating language to fetch data, so maybe something similar.

**Comment by asmitbm** [comment]
So I created two different versions of feedstock-outputs page:

## Detailed cards:
![Frame 28](https://github.com/conda-forge/conda-forge.github.io/assets/81866614/a9f24952-cf67-453e-b860-6a40330c872a)

This contains info like name of the feedstock, number of downloads and license. If there's any other relevant info present, I can include that as well. I'm not sure if this data can be taken from https://conda-metadata-app.streamlit.app/?q=conda-forge

## Name cards
![Frame 29](https://github.com/conda-forge/conda-forge.github.io/assets/81866614/58f79dd7-a5c8-4d99-badf-f5b7bef02966)

This is just the modified version of current UI. Instead of feedstocks appearing one under the another, I have arranged them in 3 columns. Although I feel like there's too much gradient on this page, so we can just use primary teal color.

**Comment by jaimergp** [comment]
The primary usage of this page is to locate which feedstocks are generating a given package. So as an user I'd like to:

* Search by package name and obtain the feedstock name(s) producing it. The relationship must be clear in the UI. I should be able to quickly understand that "package A" is produced by "feedstock A". However, when I search for "package B" I will see that it can be generated by both "feedstock B1" and "feedstock B2".
* Autocomplete on the search bar would be awesome. Alternatively, the "filter as I type" behaviour is also good.

Note we have like 20k feedstocks so take into account the amount of HTML that needs to be rendered per item. It can get heavy. To that end, I think a simple table would be enough. 

While I love the info-rich cards, I don't think we can fetch the remote metadata in a performant way to display things like number of downloads or things like that, so let's stick to the metadata that it's provided in `feedstock-outputs` for now (package name, feedstock name).

**Comment by jaimergp** [comment]
Status update:

- After migrating the homepage, [we have now migrated the blog too](https://conda-forge.org/blog). This supersedes the previous system deployed from [`conda-forge/blog`](https://github.com/conda-forge/blog) (now archived). Contributing a blog post is as simple as sending a PR in this repo with a new markdown file under [`blog/`](https://github.com/conda-forge/conda-forge.github.io/tree/main/blog).

My next item will be the announcements. Right now, this is a [single RST page](https://github.com/conda-forge/conda-forge.github.io/blob/main/sphinx/src/user/announcements.rst) under the `user/` docs. Some extra machinery has been added to generate the RSS feed. My naive migration plan would be to:

1. Split the single announcements page into one post per announcement.
2. Create a new "blog-like" instance under `news/`. This will automatically generate a RSS feed. [^sidebar]
3. Redirect `/docs/user/announcements.html` to `/news/`. Same for the RSS feed.

However, I'm also tempted to merge the announcements into the current blog itself, and simply label each post type differently. Announcements would have a `news` tag, and the blog posts could be labeled as `blog` or `post`. Not sure if simpler or more intricate, but it would remove the need to differentiate between announcements and blog posts. It's not like we have a lot of throughput anyway (specially in the last year). 

[^sidebar]: Note: the current Docusaurus blog plugin doesn't allow for much sidebar customization, so we won't be able to have the dates in the sidebar links, but this is being [worked on](https://github.com/facebook/docusaurus/issues/5461). 

---

This is how it currently looks like in my local prototype:

A single announcement:

![image](https://github.com/conda-forge/conda-forge.github.io/assets/2559438/270436df-8762-4795-ad0a-91173e8cda95)

All announcements:

![image](https://github.com/conda-forge/conda-forge.github.io/assets/2559438/7a217902-7c57-42cb-9a80-cfd61d9c5a18)


The archive page:

![image](https://github.com/conda-forge/conda-forge.github.io/assets/2559438/61ca0430-8805-4793-9fa1-704ff9ffc0b6)


Thoughts?

**Comment by jaimergp** [comment]
More updates:

* Announcements merged to `/news`
* Feedstock-outputs merged to `/packages`

Coming next: community section.

**Comment by jaimergp** [comment]
Latest updates:

* `/docs` is rendered with Docusaurus now (Sphinx behind the scenes)
* `/search` configured with algolia
* Non-invasive statistics configured with GoatCounter
* Netlify previews in each PR

**Comment by jaimergp** [comment]
Latest updates:

* All Sphinx content moved to Docusaurus
* conda-metadata-app links added to `/packages`
* New status dashboard PR available at https://github.com/conda-forge/conda-forge.github.io/pull/2090 - feedback welcome!

**Comment by jaimergp** [comment]
Latest updates:

* New /status dashboard now live!

**Comment by jakirkham** [comment]
Nice work! 👏

Submitted a couple PRs tweaking little things in the status page. Overall find it very clean and nice to read/explore! 🤩

**Comment by jakirkham** [comment]
In terms of the blog/announcement point above, would suggest we keep them separate. They serve different purposes and expect it is easier for user to consume what they want if split them out

As to blogpost activity, think we can pick this up. There a number of things over the last year (or even past few months), which would benefit from a blogpost (website improvements, CI improvements, `.conda` packages, CUDA 12, etc.). We probably just need to get in the habit of cranking through these
