### ISSUE TITLE
Tracking issue to enable rattler-build in conda-forge

### ISSUE THREAD

**Issue by wolfv** [conda-forge/conda-forge.github.io#2035]
I would like work towards enabling `rattler-build` on conda-forge and the new recipe format in Q1 2024.

This is a tracking issue for the remaining tasks:

- [ ] Stabilize recipe format and "rendered" recipe format. For this we mainly use the CEP process:
 - [ ] https://github.com/conda-incubator/ceps/pull/56
 - [ ] https://github.com/conda-incubator/ceps/pull/57
- [ ] Make conda-smithy aware of the new recipe format
- [ ] Make the bots aware of the new recipe format

**Comment by 0xbe7a** [comment]
- [ ] [Adapt `conda-forge-ci-setup`](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=831570&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=986b1512-c876-5f92-0d81-ba851554a0a3&l=370)

**Comment by beckermr** [comment]
I want to comment that we should not have to adapt conda-forge-ci-setup to anything. Besides calling rattler-build itself, everything else should be made compatible including where packages are output. Otherwise, people are going to run into all sorts of weird issues when adopting it.

**Comment by 0xbe7a** [comment]
When building a package `conda-forge-ci-setup` expects a (possibly) empty folder for the build-platform and noarch iirc. I would argue that `conda-forge-ci-setup` should just discover all output architectures. But this requires changing < 10 lines of code.

**Comment by beckermr** [comment]
Discovering all outputs is IMHO a security issue.

**Comment by 0xbe7a** [comment]
Can you explain why?

**Comment by jaimergp** [comment]
>  Make conda-smithy aware of the new recipe format
>  Make the bots aware of the new recipe format

@xhochy, @beckermr, @Hind-M and I discussed this in the last infra monthly. Some of the items that came up (please correct me if I am misremembering):

- The current bot infra (including regro/cf-scripts and conda-smithy) assume `meta.yaml`-like recipe contents in many places. Adjusting the code to be compatible with the upcoming `recipe.yaml` format might be tricky without a significant refactor. At that point, other benefits might be within reach, so we might be able to fix / improve certain extra aspects of the infra at a relatively small cost.
- New `recipe.yaml` revisions might be added in the future. It might be worth considering having an abstraction layer with versioned recipe formats, including a "backend" for `meta.yaml`. This could be one way to tackle the problem.
- While recipe rendering and the "time-to-build.sh" metrics will be significantly better with rattler-build, we will still need to pay the set-up times for a base `conda` installation because most of the infra uses that (e.g. conda-forge-ci-setup). One possible way to accelerate this part is to revisit @mariusvniekerk's idea of using lockfiles to provision the base environments.

**Comment by pavelzw** [comment]
What is contained/needed in the "`base` conda installation"?
`rattler-build` is a single statically linked binary that can also upload to anaconda.org. If only building and uploading is needed, we could also just download this single binary...

**Comment by nichmor** [comment]
https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/316 was merged and started support rattler-build for upload

**Comment by tdejager** [comment]
Current status and issues, we are working on them now, this should supersede @wolf list above:

Done:
- Allow to up update teams in `recipe.yaml: https://github.com/conda-forge/conda-forge-webservices/pull/630
- Add `recipe.yaml` support in staged-recipes: https://github.com/conda-forge/staged-recipes/pull/26981
- Trigger feedstock generation for `recipe.yaml:  https://github.com/conda-forge/admin-requests/pull/1030

Doing:
- Add support for `recipe.yaml` in: https://github.com/conda-forge/admin-migrations
- Add linting of recipe.yaml in conda-simity:  https://github.com/conda-forge/conda-smithy/pull/1979
- Fill graph based on recipe-yaml in cf-scripts: https://github.com/regro/cf-scripts/pull/2845 and https://github.com/regro/cf-scripts/pull/2851
- Fix staged-recipe build CI: https://www.notion.so/prefixdev/Fix-the-staged-recipe-build-CI-62e5de248a3c44eeb568e77bbf55e68a?pvs=4

Not Started:
* Update version in recipe.yaml for `cf-scripts`
* Add `parse_recipe_yaml in `cf-scripts`
* "Add user command should update `recipe.yaml`"
* Add linting of `recipe.yaml` in `conda-forge-webservices`

**Comment by h-vetinari** [comment]
conda-forge-ci-config currently [pins](https://github.com/conda-forge/conda-forge-ci-setup-feedstock/blob/51ebda671d7f609fd94d3b80c4754dcaa9a2754f/recipe/meta.yaml#L85) `rattler-build-conda-compat >=0.0.2,<1.0.0a`, which will presumably have to be fixed now that other parts like smithy are starting to require >1.
