### ISSUE TITLE
[META] Status page improvements

### ISSUE THREAD

**Issue by jaimergp** [conda-forge/conda-forge.github.io#2137]
Just so we don't miss these pieces of feedback shared in #2090 and later:

- [x] https://github.com/conda-forge/conda-forge.github.io/issues/2135
- [x] https://github.com/conda-forge/conda-forge.github.io/issues/2132
- [x] [Contrast issues in migration details in dark mode](https://github.com/conda-forge/conda-forge.github.io/pull/2090#issuecomment-1988228279): https://github.com/conda-forge/conda-forge.github.io/pull/2239
- [x] Wheel-click or "Open link in new tab" action on any migration will take you back to the migrations overview, not the details: https://github.com/conda-forge/conda-forge.github.io/pull/2235
- [x] Incident titles do not render backticks: https://github.com/conda-forge/conda-forge.github.io/pull/2229
- [X] Migration details table loads up with all entries filtered out. Would be better to either show all by default, or at least print a message that says how many items are filtered out so users don't believe that there are no items: https://github.com/conda-forge/conda-forge.github.io/pull/2237
- [x] add [total children](https://github.com/conda-forge/conda-forge.github.io/issues/2137#issuecomment-2094059627) & sort feedstocks by it
- [x] [width](https://github.com/conda-forge/conda-forge.github.io/issues/2137#issuecomment-2106532161) of stacktrace foldout: https://github.com/conda-forge/conda-forge.github.io/pull/2230
- [x] display [paused](https://github.com/conda-forge/conda-forge.github.io/issues/2137#issuecomment-2113312542) migrators in status page
- [x] fix "not redirecting properly" when [using](https://github.com/conda-forge/conda-forge.github.io/issues/2137#issuecomment-2113319504) link to status page: https://github.com/conda-forge/conda-forge.github.io/pull/2235
- [x] version status errors need same formatting w/ details as migration ones: https://github.com/conda-forge/conda-forge.github.io/pull/2234
- [ ] revisit colour scheme for migrator stati (c.f. [here](https://github.com/conda-forge/conda-forge.github.io/issues/2137#issuecomment-2294793097))
- [ ] consider changing progress bar to "PRs merged", not "PRs opened" (c.f. [here](https://github.com/conda-forge/conda-forge.github.io/issues/2137#issuecomment-2303047226))

@GabrielaVives proposed these UX improvements in #2090:

- [x] Migration table sorts all categories ([see alternative proposal with single row of titles above, and category separators](https://github.com/conda-forge/conda-forge.github.io/pull/2090#issuecomment-1966619530))
- [x] [Migration details table colors, tooltips and visibility](https://github.com/conda-forge/conda-forge.github.io/pull/2090#issuecomment-1979121823):
  - [x] https://github.com/conda-forge/conda-forge.github.io/pull/2239

**Comment by h-vetinari** [comment]
I'd like to have the number of children per feedstock in the migrator overviews again, and use that for sorting the tables (with a secondary sort based on the feedstock name; currently this is using reverse alphabetical sorting, which is weird). Even nicer would be to have clickable columns for sorting (e.g. one can choose between num_children and alphabetical; both have their uses).

**Comment by h-vetinari** [comment]
I consider the lack of number of total children to be a regression compared to the previous status page (and the reverse alphabetical ordering is annoying too). In particular, it's going to make it hard to know where to focus attention in a big migration like numpy (2800 feedstocks).

I noted this a month ago so I'm wondering if someone (@afshin?) still feel responsible for the new status page, or is this now up to us (=cf/core)?

**Comment by h-vetinari** [comment]
Just scrolling down to the incidents, I think we should remove the "major outage" / "maintenance" etc. from any incidents that have been resolved. Otherwise it looks confusing - there's a very loud colour saying "problem!", and then you need to read the date and realize it's not a problem anymore. Also there's still a "This is a test" major outage, which should just be removed.

**Comment by jakirkham** [comment]
The confusing bit is there is no separation between active and past incidents. They are all just incidents

Maybe we should just move past incidents somewhere else and just have a link there

**Comment by jaimergp** [comment]
Active ones show up at the very top. Maybe the bottom section should be called Past incidents?

**Comment by jakirkham** [comment]
That's certainly an option

Would note the current incident was also showing up at the bottom. So we may want to change that behavior if we retitle it

Is there an expiration period where some past incidents drop from the list?

**Comment by h-vetinari** [comment]
@jaimergp, I think possibly as a consequence of #2176, the fold-outs for unsolvable packages in the migration aren't across the full width anymore:

![image](https://github.com/conda-forge/conda-forge.github.io/assets/33685575/8bb940e0-ac2b-45f4-b524-c3ad42459e49)

**Comment by jaimergp** [comment]
oops, yes, some colspan needs a bump there

**Comment by jakirkham** [comment]
Observed an issue with how status incidents that include URLs are rendered (no hyperlink is added): https://github.com/conda-forge/conda-forge.github.io/issues/2181

**Comment by h-vetinari** [comment]
I noticed that paused migrations do not show up in the status page. These should not be filtered out. Often, a pause is just to help debug something, including e.g. which set of feedstocks the migrator is targetting.

**Comment by h-vetinari** [comment]
Also, I regularly get the following when I click on either of these:

![image](https://github.com/conda-forge/conda-forge.github.io/assets/33685575/09c7a3f1-4dbc-4bd3-9783-e3e3e9c36c74)


![image](https://github.com/conda-forge/conda-forge.github.io/assets/33685575/1483ef22-ceb5-4d11-840a-5e88bfd84ff2)

**Comment by jaimergp** [comment]
> I noticed that paused migrations do not show up in the status page.

Do you have an example of a paused migration (now or in the past)? Trying to find the bit to check in the JSON payloads.

**Comment by h-vetinari** [comment]
the numpy2 migration was paused until ~12h ago - does that help? If not, we can merge https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5855 as paused.

**Comment by jaimergp** [comment]
Hm, I see the `paused: true` part in the migration file, but the JSON payloads don't show anything that indicates the paused status as far as I can see. We might need to add that boolean somewhere. It even shows up as ["closed" if paused](https://github.com/regro/cf-graph-countyfair/commit/717d71bf6256daa07933401aa89799b24072f6f2#diff-dc3081149060f61c5c0b3c62ff60349e74b681739446720aa4a556906a71572c), I think?

**Comment by HaudinFlorence** [comment]
@jaimergp Concerning the paused migrators status, is it possible to have more information about it ?

**Comment by jaimergp** [comment]
That requires some backend work in the status payloads, I think. Let's prioritize other frontend-only fixes first. "version status errors need same formatting w/ details as migration ones" sounds simple. This is the problem:

<img width="538" alt="image" src="https://github.com/user-attachments/assets/e5d023a5-66b0-4c51-ace0-0c6c61a6ae28">

I think we can use the same Markdown approach there.

**Comment by HaudinFlorence** [comment]
I am adding here two gif to have on a overview of the rendering
[Screencast from 24-07-2024 16:07:47.webm](https://github.com/user-attachments/assets/7c9d6a66-3364-4ac9-b844-24d52ae18584)
[Screencast from 24-07-2024 16:10:52.webm](https://github.com/user-attachments/assets/70e7890a-03a6-4f2e-86f2-bc2cfad539ee)

**Comment by jaimergp** [comment]
> @jaimergp Concerning the paused migrators status, is it possible to have more information about it ?

FYI the backend work is ongoing: https://github.com/regro/cf-scripts/pull/2886

**Comment by h-vetinari** [comment]
Haven't been able to follow all the work going into the status page (aside from noticing some changes of course); in any case, thanks for the work on this! Table layout is currently broken though

![image](https://github.com/user-attachments/assets/f8062913-c358-4ceb-96f7-7543b826bc38)

Also, the issue from this [comment](https://github.com/conda-forge/conda-forge.github.io/issues/2137#issuecomment-2113319504) (links back to main status page not working) has only been working intermittently at best, and actually gotten worse recently in that it seems to redirect to a non-HTTPS page:

![image](https://github.com/user-attachments/assets/63da7b56-2744-4329-95db-c9902d59e1fa)

**Comment by jaimergp** [comment]
That's so weird. The PR preview for the latest changes does render properly: https://deploy-preview-2250--conda-forge-previews.netlify.app/status/

**Comment by afshin** [comment]
The latest migrations table PR (https://github.com/conda-forge/conda-forge.github.io/pull/2250) appears to not be deployed.

**Comment by jaimergp** [comment]
It does look like that it did go through ([logs](https://github.com/conda-forge/conda-forge.github.io/actions/runs/10188070110)), but I've retriggered it anyway.

**Comment by afshin** [comment]
The separate tables with only one header was from https://github.com/conda-forge/conda-forge.github.io/pull/2248, so what I currently see deployed appears to be that PR's iteration.

**Comment by afshin** [comment]
Hmm wait a minute, in #2250, we actually did a `git reset` to an earlier commit and then we changed the UI, in effect deleting #2248 from history. Is there a chance that when it got merged ... it resurrected that history? I didn't think a merge would do this but now I am questioning it ...

**Comment by jaimergp** [comment]
That's my thinking too. That the gh-pages branch is suffering from some git weirdness... Let me debug locally with `main` and see if we can reset `gh-pages`.

**Comment by jaimergp** [comment]
Yea, can reproduce locally. `main` has this weird hybrid solution after the merge. We'll need to submit a PR to amend.

**Comment by jaimergp** [comment]
See https://github.com/conda-forge/conda-forge.github.io/pull/2253

**Comment by jaimergp** [comment]
Should be working now.

**Comment by jaimergp** [comment]
> Also, the apparent fix for the issue from this https://github.com/conda-forge/conda-forge.github.io/issues/2137#issuecomment-2113319504 (links back to main status page not working) has only been working intermittently at best, and actually gotten worse recently in that it seems to redirect to a non-HTTPS page (sometimes).

I can't reproduce this :/ I do see that the breadcrumbs point to `/status` (no trailing slash). So maybe it's a redirect bug in the browser? Which one are you using @h-vetinari?

**Comment by afshin** [comment]
I confirm that you've fixed it!

**Comment by afshin** [comment]
I couldn't get the breadcrumb links to break in Firefox, Chrome, or Safari (on macOS).

Is there a chance you were hitting a version that was cached in your browser, @h-vetinari? The page has been simplified to basically have a static file for every single path, so the behavior you're seeing seems to me like a caching issue, perhaps.

**Comment by h-vetinari** [comment]
> Is there a chance you were hitting a version that was cached in your browser, @h-vetinari? The page has been simplified to basically have a static file for every single path, so the behavior you're seeing seems to me like a caching issue, perhaps.

I've noticed this over the last couple of days since the fix was deployed, and across a couple browser restarts. Now of course I cannot reproduce anymore either (though I could a couple hours ago), but I'll comment if it happens again. I'm on the latest Firefox btw.

**Comment by jakirkham** [comment]
Another useful thing for the status page would be adding a few more labels for context. For example it might help when in addition to priority we include the context where the issue is happening?

Alternatively we might consider giving the titles of issues more prominence instead of the labels. Looking at a recent outage am seeing major outage broadcast, but don't quite know what it is about without reading further. We could soften this the major portion to help people understand what they are looking at first

<img width="1840" alt="Screenshot 2024-08-02 at 2 55 50 PM" src="https://github.com/user-attachments/assets/e0b0dbba-e76d-4f48-8c97-ea5c66bea2f0">

**Comment by h-vetinari** [comment]
> * [x] [Migration details table colors, tooltips and visibility](https://github.com/conda-forge/conda-forge.github.io/pull/2090#issuecomment-1979121823):
>   * [x] https://github.com/conda-forge/conda-forge.github.io/pull/2239

I commented on the colour scheme changes [elsewhere](https://github.com/conda-forge/conda-forge.github.io/issues/2243#issuecomment-2266260967) already, but I wanted to reiterate here that I don't see how various shades of grey are more accessible (e.g. for vision-impaired people)

![image](https://github.com/user-attachments/assets/fd06e3b2-e141-4da2-9971-08ff1cb5410f)

than the much more distinct colours we had previously

![354756997-6d79c9d2-59fc-4e6d-95b4-9a36c788633c](https://github.com/user-attachments/assets/e22f510a-8c1e-4a81-bd11-10be17ae4e57)

I picked the colours from the bubbles[^1] and [put them](https://www.aremycolorsaccessible.com/palette?colors=%23648e66&colors=%238d949e&colors=%23ccd0d5&colors=%23ebedf0&colors=%23ffb74d&colors=%23fb565b) into aremycolorsaccessible (found by random googling as I was looking for turbo, more below), and while I can't vouch for their methodology, it has pretty clear opinions:

![image](https://github.com/user-attachments/assets/3d0338ff-fa0a-48db-9535-4aba8682f7c9)

I'm certainly not a web developer, or expert for UX and accessibility, but I do remember how google [developed](https://research.google/blog/turbo-an-improved-rainbow-colormap-for-visualization/) a new colormap (called "turbo") with accessibility in mind a while back, and naïvely taking that as a reference would seem like we should if anything have starker colours rather than more subdued ones: 

![image](https://github.com/user-attachments/assets/a67b000e-5a36-45a7-a89e-6b1682d47dcf)

Taking the values {0.0, 0.16, 0.33, 0.5, 0.66, 0.83, 1.0}  from their colourmap would give us 6 colours that are in some ways ideally spaced across various metrics (e.g. across various vision impairments, for details see article).


[^1]: because it's hard for me to tell where `--ifm-color-emphasis-600` is actually defined; some colours are defined in [`custom.css`](https://github.com/conda-forge/conda-forge.github.io/blob/main/src/css/custom.css), but not all

**Comment by h-vetinari** [comment]
One other point that I think is confusing: the progress percentage of a migration should be "PRs merged", not "PRs opened". As an extreme example, the ruby migration _looks_ almost done (14/16 opened), but only 2(!) have been merged. That migration has separate [problems](https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/4805), but the point is that having a PR open says nothing about whether the migration is close to finished (aside perhaps from the POV of the bot, but that's not what users/maintainers are most interested in).

**Comment by jaimergp** [comment]
Thanks for the feedback @h-vetinari. I'll create new issues for your comments and reply there to keep things actionable.

**Comment by jaimergp** [comment]
I've closed this issue to better track what to do next. The original intent here was to collect existing feedback in the first PR, but we ended up collecting more items and was difficult to watch the discussion. Thanks everyone who reported their feedback and specially to @HaudinFlorence and @afshin who implemented the fixes!
