### ISSUE TITLE
RFC: Add new target: emscripten-wasm32

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/conda-forge.github.io#2244]
Adding a new target is a pretty big deal, but there are good reasons to do so.

## Background

WASM (Web Assembly) is a powerful idea to run essentially any code in a browser on top of JavaScript. The idea has proven to be very successful because it allows essentially running arbitrary things in a browser, without the user having to explicitly install stuff.

This becomes even more powerful when combined with something like jupyter, which can serve the notebooks (and save the state), while delegating the actual computations, to the client browser, thus allowing massive scalability.

## Particularities of WASM as a target:
* no real OS
* no real file system
* need browser (or node.js) to run
* separate build infrastructure (`gcc` -> `emcc`; `configure` -> `emconfigure`; `make` -> `emmake`; `cmake` -> `emcmake`)

## Consequences – Overall

Since everything lives in the browser (i.e. we don't have a full-fledged OS), we need to do some extra work, like installing an environment elsewhere, and mounting this into a virtual filesystem. This especially has the consequence of needing a build/target split also or the test environment, i.e. one architecture that runs the required infrastructure for the headless browser (matching the CI agent), and one where we actually install the emscripten-wasm32 package.

## Consequences – in more detail

Nomenclature:
* in the javascript world, a "main module" roughly corresponds to what we consider a binary, and a "side module" to a shared library; more details [here](https://emscripten.org/docs/compiling/Dynamic-Linking.html#overview-of-dynamic-linking) and [here](https://emscripten.org/docs/compiling/Dynamic-Linking.html#dynamic-linking)

Packaging:
* Binaries generally come as a split between a `foo.wasm` file and a `foo.js` file, where the javascript part can roughly be considered to set up the scaffolding (virtual filesystem etc.). 
* CMake doesn't [support](https://gitlab.kitware.com/cmake/cmake/-/issues/20745) this split, and does not copy both files natively; this needs either modifications to `CMakeLists.txt` to insert an `if emscripten: copy...` or handling this in the build script directly
* The way node loads a binary sets up some global state (e.g. related to the allocator) that gets clobbered if several are loaded. This then results in segfaults and other weird behaviour. To counter act this, we need to compile with `-sMODULARIZE=1`
* by default (or at least the most widespread), wasm is a 32bit target. To use large ints, we need to set `-sWASM_BIGINT` globally.

Runtime:
* The default is to run WASM from a headless browser, but it's also possible to use node.js (which can help for testing compiled binaries in particular)
* There's also https://wasi.dev, which users an interface to the host system to run WASM (rather than the browser), but at last check that didn't support shared libraries.

Filesystem:
* Unlike containers, the file-system in WASM isn't "mounted", but is a one-way copy (during setup) to the JavaScript-based virtual filesystem
* There is also a "[WasmFS](https://emscripten.org/docs/api_reference/Filesystem-API.html#new-file-system-wasmfs)" in emscripten

No subprocesses:
* By default, it's not simply possible to fork or call a subprocess. There are some work-arounds, but those need care as the javascript world does this asynchronously, while the python side is synchronous. For the time being, we should not assume that we'll be able to package things that need to execute subprocesses.

## Current state

There is https://emscripten-forge.org/, which already publishes a handful of packages to a separate channel, from an open-source [monorepo](https://github.com/emscripten-forge/recipes) of recipes.

References:
* https://github.com/emscripten-core/emsdk (compiler)
* https://github.com/emscripten-forge/pyjs-code-runner (to python in javascript)
* https://github.com/conda-forge/playwright-feedstock (to code in headless browser)
* emscripten-forge [docs](https://github.com/emscripten-forge/recipes/blob/main/docs/development/adding_packages.md) on how to build packages
* Open [TODOs](https://github.com/emscripten-forge/recipes/labels/conda-forge-migration) in emscripten-forge related to this effort
* General [checklist](https://github.com/conda-forge/conda-forge.github.io/issues/1123#issuecomment-668399522) for adding new architecture to conda-forge

Other things in this space:
* [pyodide](https://pyodide.org/en/stable/)

# Vision

* Build as many packages as possible for emscripten-wasm32, as for any other architecture, become "regular target" in conda-forge
* Serve 1000s of notebooks from a single server (because each consuming browser takes care of the actual execution).

# Proposed Ramp-up (duration is open question)

* Support running in all major browsers
* Cross-compile from linux to emscripten
* Only build for a single python version initially
* Only publish to a specific label, not conda-forge `main`

____

## Tasks

* Installer support
  * [x] conda itself: https://github.com/conda/conda/pull/13962
  * [ ] mamba: https://github.com/mamba-org/mamba/issues/3291
  * [x] pixi: https://github.com/prefix-dev/pixi/commit/34105dfd67a865118289c76fba9adb2c6cf22b80
  * [x] rattler: https://github.com/mamba-org/rattler/pull/333
  * [ ] CEP for required testing infrastructure: https://github.com/conda/ceps/pull/84
* conda-forge infrastructure
  * [ ] https://github.com/conda-forge/conda-forge.github.io/issues/2035 (meta); selection of relevant PRs:
    * [x] https://github.com/conda-forge/conda-smithy/pull/1876
    * [x] https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/325
    * [x] https://github.com/conda-forge/admin-migrations/pull/109
  * [ ] add custom arch migration (like for osx-arm64)
* compilers
  * package emscripten compiler from [here](https://github.com/emscripten-core/emsdk)?
  * other tooling?
* testing
  * [x] package [pyjs-code-runner](https://github.com/conda-forge/pyjs_code_runner-feedstock)
  * [x] package [playwright](https://github.com/conda-forge/playwright-feedstock)
* initial set of packages
  * [ ] everything leading up to python/pytest/...
  * [ ] eventually: start migration

**Comment by bollwyvl** [comment]
> everything leading up to python

With [PEP 783](https://peps.python.org/pep-0783) fully accepted, several Python package upstreams are adding `pyemscripten_${YEAR}_${PATCH}*.whl` to their build matrices and uploading to PyPI, e.g. [ast-serialize](https://pypi.org/project/ast-serialize/#ast_serialize-0.6.0-cp39-abi3-pyemscripten_2026_0_wasm32.whl), [librt](https://pypi.org/project/librt/#librt-0.12.0-cp314-cp314-pyemscripten_2026_0_wasm32.whl) to PyPI... 

> pytest/...

... though thus far not a lot of _testing_ of said wheels. 

That being said, from a conda-forge testing perspective, we have a number of runtimes that beyond full browsers (e.g. [firefox](https://github.com/conda-forge/firefox-feedstock) and [geckodriver](https://github.com/conda-forge/geckodriver-feedstock)) like the emscripten-compatible [mini-racer](https://github.com/conda-forge/mini-racer-feedstock) or WASI flavors like [wasmer](https://github.com/conda-forge/wasmer-feedstock/) and [wasmtime-py](https://github.com/conda-forge/wasmtime-py-feedstock/).
